baseurl      = "https://nervous-brown-43faa8.netlify.app/"
title        = "Carolina Soares"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs"
PygmentsCodeFences = true
PygmentsStyle = "monokai"


buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software Developer | Carbon-based bipedal life form."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Software Developer | Carbon-based bipedal life form."
  keywords = "homepage, blog, developer, elasticsearch, java, python, javascript, node, react, linux, logs"
  images = [""]

  # Theme
  defaultTheme = "dark"
  themeColor = "#252627"

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/carolinasrc_"

  [[params.social]]
    name = "github"
    url  = "https://github.com/carolinasrc"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/carolinases/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    subtitle  = "Hello Friend NG Theme"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
